version: '3.9'

services:
  mongodb-product:
    image: mongo
    container_name: mongodb_product_container
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ecomm_product_db
      MONGO_INITDB_ROOT_USERNAME: product
      MONGO_INITDB_ROOT_PASSWORD: productpass
    volumes:
      - product_mongodb_data:/data/db


  mysql-customer:
    image: mysql:latest
    container_name: mysql_customer_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ecomm_customer_db
      MYSQL_USER: customer
      MYSQL_PASSWORD: customerpass
    volumes:
      - customer_mysql_data:/var/lib/mysql
      - ./init-files/customer-service/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always


  mysql-order:
      image: mysql:latest
      container_name: mysql_order_container
      ports:
        - "3307:3306"
      environment:
        MYSQL_ROOT_PASSWORD: rootpassword
        MYSQL_DATABASE: ecomm_order_db
        MYSQL_USER: order
        MYSQL_PASSWORD: orderpass
      volumes:
        - order_mysql_data:/var/lib/mysql
        - ./init-files/order-service/init.sql:/docker-entrypoint-initdb.d/init.sql
      restart: always


  mysql-payment:
      image: mysql:latest
      container_name: mysql_payment_container
      ports:
        - "3308:3306"
      environment:
        MYSQL_ROOT_PASSWORD: rootpassword
        MYSQL_DATABASE: ecomm_payment_db
        MYSQL_USER: payment
        MYSQL_PASSWORD: paymentpass
      volumes:
        - payment_mysql_data:/var/lib/mysql
        - ./init-files/payment-service/init.sql:/docker-entrypoint-initdb.d/init.sql
      restart: always

volumes:
  product_mongodb_data:
  customer_mysql_data:
  order_mysql_data:
  payment_mysql_data:

